# Generated by Django 4.1.6 on 2024-04-12 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AWSAccessDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("access_key", models.CharField(max_length=255)),
                ("secret_key", models.CharField(max_length=255)),
                ("region", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="AzureAccessDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subscription_id", models.CharField(max_length=255)),
                ("client_id", models.CharField(max_length=255)),
                ("secret", models.CharField(max_length=255)),
                ("tenant", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("schedule", models.CharField(max_length=255)),
                ("action", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="UniversalTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=255)),
                ("value", models.CharField(max_length=255)),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tagman.schedule",
                    ),
                ),
            ],
        ),
    ]
