# Generated by Django 4.1.6 on 2024-04-12 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tagman", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="universaltag",
            name="schedule",
        ),
        migrations.AddField(
            model_name="universaltag",
            name="schedules",
            field=models.ManyToManyField(to="tagman.schedule"),
        ),
    ]
