# Generated by Django 5.0.6 on 2024-10-06 11:16
from pgvector.django import VectorExtension


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = []

    operations = [VectorExtension()]
