# Generated by Django 5.0.6 on 2024-10-06 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vecman", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="text_data",
            field=models.TextField(default="Hello world"),
            preserve_default=False,
        ),
    ]
