# Generated by Django 5.0.6 on 2024-10-06 12:07

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vecman", "0003_file_text_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="embedding",
            field=pgvector.django.vector.VectorField(
                blank=True, dimensions=384, help_text="Vector embeddings", null=True
            ),
        ),
    ]
