# Generated by Django 5.0.6 on 2024-10-06 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vecman", "0004_alter_file_embedding"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="file_type",
            field=models.CharField(
                choices=[("txt", "Text"), ("img", "Image")],
                default="txt",
                max_length=10,
            ),
        ),
    ]
