# Generated by Django 4.1.6 on 2024-04-04 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transformer", "0003_etlinput_name_etloutput_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="etloutput",
            name="job",
        ),
    ]
