# Generated by Django 4.1.6 on 2023-11-19 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("graph", "0003_alter_graphpoint_label"),
    ]

    operations = [
        migrations.AddField(
            model_name="graph",
            name="shift_count",
            field=models.IntegerField(default=0),
        ),
    ]
