# Generated by Django 4.1.6 on 2024-01-05 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("graph", "0005_graph_primary_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="graph",
            name="primary_color",
            field=models.CharField(default="#68729e", max_length=16),
        ),
    ]
