# Generated by Django 4.1.6 on 2023-11-16 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('l4mbda', '0002_job_storage'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='next_job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='l4mbda.job'),
        ),
    ]
