# Generated by Django 4.1.6 on 2023-11-16 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("l4mbda", "0003_job_next_job"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="next_job",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="l4mbda.job",
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="storage",
            field=models.TextField(blank=True, default="", null=True),
        ),
    ]
