# Generated by Django 4.1.6 on 2023-11-13 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculus", "0002_inferencemodel_output"),
    ]

    operations = [
        migrations.AddField(
            model_name="inferencemodel",
            name="input",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="inferencemodel",
            name="metadata",
            field=models.TextField(blank=True, null=True),
        ),
    ]
