# Generated by Django 4.1.6 on 2024-04-06 14:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('k8smanager', '0002_pod_node'),
    ]

    operations = [
        migrations.AddField(
            model_name='pod',
            name='ip_address',
            field=models.GenericIPAddressField(default='10.69.0.1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pod',
            name='node',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='k8smanager.node'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pod',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
