# Generated by Django 4.1.6 on 2024-04-06 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('k8smanager', '0004_ingress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingress',
            name='rules',
            field=models.TextField(),
        ),
    ]
