# Generated by Django 4.1.6 on 2024-04-07 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("k8smanager", "0006_ingress_host"),
    ]

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("namespace", models.CharField(max_length=255)),
                ("cluster_ip", models.GenericIPAddressField()),
                ("external_ip", models.GenericIPAddressField()),
                ("type", models.CharField(max_length=255)),
                ("ports", models.TextField()),
                (
                    "cluster",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="k8smanager.cluster",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Deployment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("namespace", models.CharField(max_length=255)),
                ("replicas", models.IntegerField()),
                ("available_replicas", models.IntegerField()),
                ("unavailable_replicas", models.IntegerField()),
                ("strategy", models.TextField()),
                ("template", models.TextField()),
                (
                    "cluster",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="k8smanager.cluster",
                    ),
                ),
            ],
        ),
    ]
