# Generated by Django 4.1.6 on 2024-04-07 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("k8smanager", "0007_service_deployment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deployment",
            name="available_replicas",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="deployment",
            name="unavailable_replicas",
            field=models.IntegerField(null=True),
        ),
    ]
