# Generated by Django 4.1.6 on 2024-04-07 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("k8smanager", "0008_alter_deployment_available_replicas_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="cluster_ip",
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AlterField(
            model_name="service",
            name="external_ip",
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AlterField(
            model_name="service",
            name="ports",
            field=models.TextField(null=True),
        ),
    ]
