# Generated by Django 4.1.6 on 2024-04-07 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "k8smanager",
            "0009_alter_service_cluster_ip_alter_service_external_ip_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingress",
            name="ip_address",
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AlterField(
            model_name="pod",
            name="ip_address",
            field=models.GenericIPAddressField(null=True),
        ),
    ]
