# Generated by Django 4.1.6 on 2024-04-14 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("k8smanager", "0010_alter_ingress_ip_address_alter_pod_ip_address"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="deployment",
            name="strategy",
        ),
        migrations.RemoveField(
            model_name="deployment",
            name="template",
        ),
    ]
